FIND_PATH(BLKID_INCLUDE_DIR blkid.h /usr/include/blkid
    /usr/local/include/blkid)

FIND_LIBRARY(BLKID_LIBRARY NAMES blkid PATH /usr/lib /usr/local/lib) 

IF (BLKID_INCLUDE_DIR AND BLKID_LIBRARY)
   SET(BLKID_FOUND TRUE)
ENDIF (BLKID_INCLUDE_DIR AND BLKID_LIBRARY)


IF (BLKID_FOUND)
   IF (NOT blkid_FIND_QUIETLY)
      MESSAGE(STATUS "Found blkid: ${BLKID_LIBRARY}")
   ENDIF (NOT blkid_FIND_QUIETLY)
ELSE (BLKID_FOUND)
   IF (blkid_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find blkid")
   ENDIF (blkid_FIND_REQUIRED)
ENDIF (BLKID_FOUND)
