FIND_PATH(AUPARSE_INCLUDE_DIR auparse.h /usr/include
    /usr/local/include)

FIND_LIBRARY(AUPARSE_LIBRARY NAMES libauparse.a PATH /usr/lib /usr/local/lib) 

IF (AUPARSE_INCLUDE_DIR AND AUPARSE_LIBRARY)
   SET(AUPARSE_FOUND TRUE)
ENDIF (AUPARSE_INCLUDE_DIR AND AUPARSE_LIBRARY)


IF (AUPARSE_FOUND)
   IF (NOT auparse_FIND_QUIETLY)
      MESSAGE(STATUS "Found auparse: ${AUPARSE_LIBRARY}")
   ENDIF (NOT auparse_FIND_QUIETLY)
ELSE (AUPARSE_FOUND)
   IF (auparse_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find auparse")
   ENDIF (auparse_FIND_REQUIRED)
ENDIF (AUPARSE_FOUND)
